### ISSUE TITLE
Add whitelist mechanisms

### ISSUE THREAD

**Issue by robbat2** [mgorny/glep63-check#5]
Related to #4, provide a mechanism to whitelist specific checks on specific devs.

Infra SHOULD have a paper trail for the short-term exceptions.

In this case, `whissi` has a true offline primary key, and will not be able to access it for 5 days, which will be enough time to update the expiry of the other keys.

As another upcoming example, GnuPG 2.3 plans to set ECC algorithms by default in a few months (and the spec should be revised to permit this).

**Comment by mgorny** [comment]
This doesn't belong in the tool. It has machine-readable output if you want to filter it.
